# External Application Load Balancer
#
# Routes one public HTTPS origin to two backends:
#   /api/*  -> Cloud Run (via a serverless NEG + backend service)
#   /*      -> the frontend static-site bucket (via a backend bucket)
#
# The private syllabus-files bucket is intentionally NOT wired here; it stays
# private and is only reached through signed URLs generated by Cloud Run.

# Single global anycast IP for the LB.
resource "google_compute_global_address" "lb_ip" {
    name       = "dal-syllabus-lb-ip"
    depends_on = [google_project_service.compute]
}

# ---- Frontend: backend bucket ----
# Honors the bucket's website config (index.html / 404.html). enable_cdn can be
# flipped to true later to turn on Cloud CDN with no other change.
resource "google_compute_backend_bucket" "frontend" {
    name        = "dal-syllabus-frontend-backend"
    bucket_name = google_storage_bucket.frontend.name
    enable_cdn  = false
    depends_on  = [google_project_service.compute]
}

# ---- API: serverless NEG -> backend service ----
resource "google_compute_region_network_endpoint_group" "api_neg" {
    name                  = "dal-syllabus-api-neg"
    region                = var.region
    network_endpoint_type = "SERVERLESS"

    cloud_run {
        service = google_cloud_run_v2_service.backend.name
    }

    depends_on = [google_project_service.compute]
}

resource "google_compute_backend_service" "api" {
    name                  = "dal-syllabus-api-backend"
    load_balancing_scheme = "EXTERNAL_MANAGED"

    backend {
        group = google_compute_region_network_endpoint_group.api_neg.id
    }
}

# ---- URL map: path-based routing ----
resource "google_compute_url_map" "main" {
    name            = "dal-syllabus-urlmap"
    default_service = google_compute_backend_bucket.frontend.id

    host_rule {
        hosts        = [var.domain]
        path_matcher = "main"
    }

    path_matcher {
        name            = "main"
        default_service = google_compute_backend_bucket.frontend.id

        path_rule {
            paths   = ["/api", "/api/*"]
            service = google_compute_backend_service.api.id
        }
    }
}

# ---- Managed TLS cert for the domain ----
# Stays in PROVISIONING until an A record for var.domain points at lb_ip; then it
# auto-issues (usually 15-60 min). Nothing serves HTTPS until it goes ACTIVE.
resource "google_compute_managed_ssl_certificate" "main" {
    name = "dal-syllabus-cert"

    managed {
        domains = [var.domain]
    }
}

resource "google_compute_target_https_proxy" "main" {
    name             = "dal-syllabus-https-proxy"
    url_map          = google_compute_url_map.main.id
    ssl_certificates = [google_compute_managed_ssl_certificate.main.id]
}

resource "google_compute_global_forwarding_rule" "https" {
    name                  = "dal-syllabus-https-fr"
    load_balancing_scheme = "EXTERNAL_MANAGED"
    target                = google_compute_target_https_proxy.main.id
    port_range            = "443"
    ip_address            = google_compute_global_address.lb_ip.id
}

# ---- HTTP :80 -> permanent redirect to HTTPS ----
resource "google_compute_url_map" "https_redirect" {
    name = "dal-syllabus-https-redirect"

    default_url_redirect {
        https_redirect         = true
        redirect_response_code = "MOVED_PERMANENTLY_DEFAULT"
        strip_query            = false
    }
}

resource "google_compute_target_http_proxy" "http" {
    name    = "dal-syllabus-http-proxy"
    url_map = google_compute_url_map.https_redirect.id
}

resource "google_compute_global_forwarding_rule" "http" {
    name                  = "dal-syllabus-http-fr"
    load_balancing_scheme = "EXTERNAL_MANAGED"
    target                = google_compute_target_http_proxy.http.id
    port_range            = "80"
    ip_address            = google_compute_global_address.lb_ip.id
}

# Handy outputs for the post-apply steps.
output "lb_ip" {
    description = "Point an A record for var.domain at this IP."
    value       = google_compute_global_address.lb_ip.address
}

output "cert_domain" {
    value = var.domain
}
